# -*- coding: utf-8 -*-
"""Proyecto Final del Primer Modulo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeFyAalCE9spj281W1P0BCYu0BYGpzcg
"""

!pip install -qU langchain langchain_openai langchain-core langchain-community langgraph psycopg[binary,pool]==3.2.6

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from langgraph.checkpoint.memory import MemorySaver
from langgraph.prebuilt import create_react_agent
from langchain.tools import tool
from langchain_core. prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
import requests
#from langchain_community.utilities.sql_database import SQLDatabase
#from langchain_community.agent_toolkits import SQLDatabaseToolkit

import os
with open("/content/api_key.txt") as archivo:
  apikey = archivo.read()
os.environ["OPENAI_API_KEY"] = apikey

#with open("/content/ConexionSap.txt") as archivo:
 # uribd = archivo.read()

#Creamos la conexion a la base de datos
#db_data = SQLDatabase.from_uri(uribd)

# Herramienta BD
#toolkit_bd = SQLDatabaseToolkit(db=db_data,llm=ChatOpenAI(temperature=0))
#tools_bd = toolkit_bd.get_tools()

"""##Creación de Herramientas API

### PokeAPI
"""

@tool
def extractorPokemon(name: str) -> str:
    """Con el nombre de un Pokémon retorna una cadena con sus tipos y dos habilidades, separadas por comas."""
    try:
        url = f"https://pokeapi.co/api/v2/pokemon/{name.lower()}"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        # Extraer tipos
        types = [t["type"]["name"] for t in data.get("types", [])]
        # Extraer hasta dos habilidades
        abilities = [a["ability"]["name"] for a in data.get("abilities", [])[:2]]
        # Formatear como "tipo1,tipo2,habilidad1,habilidad2"
        return ",".join(types + abilities)
    except requests.HTTPError:
        return f"Error: Pokémon '{name}' no encontrado."
    except requests.RequestException:
        return "Error al conectar con PokeAPI"

"""### LinkedIn Scraper API"""

import json
import http.client
@tool
def extractorLinkedIn(linkedin_url: str) -> str:
    """Con la URL de un perfil de LinkedIn extrae solo el resumen {summary} y titular {headline} ."""
    try:
        conn = http.client.HTTPSConnection("linkedin-data-api.p.rapidapi.com")

        headers = {
            'x-rapidapi-key': "d7ab9f8d78msh4ee5cf021e44debp14954cjsn97468c6de7c9",
            'x-rapidapi-host': "linkedin-data-api.p.rapidapi.com"
        }

        encoded_url = linkedin_url.replace("/", "%2F")
        endpoint = f"/get-profile-data-by-url?url={encoded_url}"

        conn.request("GET", endpoint, headers=headers)
        res = conn.getresponse()

        if res.status != 200:
            return f"Error: Código {res.status} al consultar LinkedIn."

        data = json.loads(res.read().decode("utf-8"))

        summary = data.get("summary", "Resumen no disponible")
        headline = data.get("headline", "Titular no disponible")

        return f"{headline}, {summary}"

    except Exception as e:
        return f"Error al procesar la solicitud: {str(e)}"

"""### Amazon API"""

@tool
def extractorProductoAmazon(query: str) -> str:
    """Eres un asistente que busca productos en Amazon por palabra clave y devuelve las 3 primeras opciones de la página 1,
    indicando título, precio, rating, URL y más. Al final pregunta si quiere saber de otro producto."""
    try:
        url = (
            "https://real-time-amazon-data.p.rapidapi.com/search"
            f"?query={requests.utils.quote(query)}"
            "&page=1"
            "&country=US"
            "&sort_by=RELEVANCE"
            "&product_condition=ALL"
            "&is_prime=false"
            "&deals_and_discounts=NONE"
        )
        headers = {
            "x-rapidapi-key": "d7ab9f8d78msh4ee5cf021e44debp14954cjsn97468c6de7c9",
            "x-rapidapi-host": "real-time-amazon-data.p.rapidapi.com"
        }
        resp = requests.get(url, headers=headers)
        resp.raise_for_status()
        data = resp.json()

        products = data.get("data", {}).get("products", [])[:3]
        if not products:
            return "No se encontraron productos para esa búsqueda."

        lines = []
        for i, p in enumerate(products, start=1):
            lines.append(
                f"{i}. Título: {p.get('product_title','N/A')}\n"
                f"   ASIN: {p.get('asin','N/A')}\n"
                f"   Precio: {p.get('product_price','N/A')} (Original: {p.get('product_original_price','N/A')})\n"
                f"   Rating: {p.get('product_star_rating','N/A')} ({p.get('product_num_ratings','N/A')} opiniones)\n"
                f"   URL: {p.get('product_url','N/A')}\n"
                f"   Foto: {p.get('product_photo','N/A')}\n"
                f"   Entrega: {p.get('delivery','N/A')}\n"
            )

        lines.append("¿Quieres buscar otro producto en Amazon?")
        return "\n".join(lines)

    except requests.HTTPError as e:
        return f"Error HTTP {resp.status_code} al consultar Amazon API."
    except requests.RequestException as e:
        return "Error al conectar con la Amazon API."

"""### API YOUTUBE MEDIA DONWLOADER"""

import urllib
@tool
def extractorAlbumes(cantante: str) -> str:
    """
    Eres un asistente que busca los últimos 3 playlists cuando te especifiquen el cantante;
    retorna solo los títulos (title) de cada playlist encontrados, separados por comas.
    """
    try:
        # Codificar el nombre para URL
        query = urllib.parse.quote(cantante)
        url = f"https://youtube-media-downloader.p.rapidapi.com/v2/search/playlists?keyword={query}&sortBy=relevance"

        # Cabeceras de RapidAPI
        headers = {
            "x-rapidapi-key": "d7ab9f8d78msh4ee5cf021e44debp14954cjsn97468c6de7c9",
            "x-rapidapi-host": "youtube-media-downloader.p.rapidapi.com"
        }

        # Llamada HTTP con requests
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        data = response.json()

        # Extraer hasta 5 títulos
        items = data.get("items", [])
        titles = [item.get("title", "<sin title>") for item in items[:5]]

        if not titles:
            return f"No se encontraron playlists para '{cantante}'."

        # Devolver en formato "título1,título2,..."
        return ",".join(titles)

    except requests.HTTPError:
        return f"Error: no se encontraron playlists para '{cantante}'."
    except requests.RequestException as e:
        return f"Error al conectar con la API: {e}"
    except ValueError:
        return "Error: la respuesta de la API no es un JSON válido."

"""### API EQUIPO DE FUTBOL"""

@tool
def posiciondejugador(futbolista: str) -> str:
      """con el nombre del futbolista retorname su posicion de juego en el campo de futbol"""
      try:
        url = "https://apifutbolista-ko6ygtybmq-wn.a.run.app/equipo?futbolista="+futbolista
        response = requests.get(url)
        if response.status_code == 200:
          return response.text
        else:
          return "Error encontrando equipo de futbol"
      except requests.exceptions.RequestException as e:
        return "Error encontrando equipo de futbol"

"""### API Tripulacion ONEPIECE"""

@tool
def obtenerTripulacion(personaje: str) -> str:
    """Dado el nombre de un personaje de One Piece, retorna el nombre de su tripulación pirata desde una API externa."""
    try:
        url = "https://apionepiece-ko6ygtybmq-wn.a.run.app/tripulacion?personaje="+personaje
        response = requests.get(url)
        if response.status_code == 200:
            return response.text
        else:
            return "Error encontrando tripulación del personaje"
    except requests.exceptions.RequestException:
        return "Error encontrando tripulación del personaje"

"""##AGENTE INTENGRANDO LAS HERRAMIENTAS"""

model = ChatOpenAI(verbose=True)
memory = MemorySaver()
#memory = ConversationBufferWindowMemory(
#    k=5,                # numero de mensajes a retener
 ##)
#construccion del prompt
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", """ Eres un asistente gentil, usa solo tus herramientas para responder las preguntas de los usuarios.
        Si no cuentas con una herramienta específica para resolver una pregunta, infórmalo claramente, indica que no puedes responder y evita realizar cualquier invocación innecesaria .
        """),

     ("human", "{messages}"),

     ]
)

tolkit = [extractorPokemon,extractorLinkedIn,extractorProductoAmazon,extractorAlbumes,posiciondejugador]
agent = create_react_agent(model, tolkit, checkpointer=memory, prompt=prompt)

config = {"configurable": {"thread_id": "abc126"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="¿en que posicion juega pedri?")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc126"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="¿en que posicion juega vinicius junior?")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc126"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="que habilidad tiene Zapdos")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="y de linkin park? ")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="y que habilidades tiene snorlax")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="y de snoop dog? ")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="quiero comprar un celular cual recomiendas")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="si quisiera saber delaptops")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

# Use the agent
config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="conoces el pokemon ditto?")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

# Use the agent
config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="y charmander?")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

# Use the agent
config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="y que me puedes decir de pikachu?")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
response = agent.invoke({"messages": [HumanMessage(content="que sabes de Mewtwo")]}, config=config)
response['messages'][-1].pretty_print()

# Use the agent
config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="que sabes de onix")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="dame los datos de hector-cardenas-camacho-197101169")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="dame informacion de este perfil https://www.linkedin.com/in/mcotrina/")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="dame informacion de este perfil https://www.linkedin.com/in/mcotrina/")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()

config = {"configurable": {"thread_id": "abc124"}}
for step in agent.stream(
    {"messages": [HumanMessage(content="dame informacion de este perfil https://www.linkedin.com/in/mcperezes/")]},
    config,
    stream_mode="values",
):
    step["messages"][-1].pretty_print()